apiVersion: v1
kind: ConfigMap
metadata:
  name: stackfood-orders-config
  labels:
    app.kubernetes.io/name: stackfood-orders
    app.kubernetes.io/part-of: stackfood
data:
  # Database Configuration
  ConnectionStrings__DefaultConnection: "Host=stackfood-db.c7u6s4akq7qg.us-east-1.rds.amazonaws.com;Port=5432;Database=stackfood_orders;Username=stackfood;Password=postgres"

  # External Services
  ExternalServices__ProductsApiUrl: "http://stackfood-products.products.svc.cluster.local:8080"

  # AWS SNS Configuration
  AWS__Region: "us-east-1"
  AWS__UseLocalStack: "false"
  AWS__SNS__OrderCreatedTopicArn: "arn:aws:sns:us-east-1:471112618001:stackfood-sns-orders-created"
  AWS__SNS__OrderCancelledTopicArn: "arn:aws:sns:us-east-1:471112618001:stackfood-sns-orders-cancelled"
  AWS__SNS__OrderCompletedTopicArn: "arn:aws:sns:us-east-1:471112618001:stackfood-sns-orders-completed-topic"

  # AWS SQS Configuration
  AWS__SQS__PaymentEventsQueueUrl: "https://sqs.us-east-1.amazonaws.com/471112618001/stackfood-sqs-payments-queue"
  AWS__SQS__ProductionEventsQueueUrl: "https://sqs.us-east-1.amazonaws.com/471112618001/stackfood-sqs-production-queue"

  # Application Settings
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8081"
