apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stackfood-orders-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /orders(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: stackfood-orders
            port:
              number: 8081
