apiVersion: v1
kind: Service
metadata:
  name: stackfood-orders
  labels:
    app.kubernetes.io/name: stackfood-orders
    app.kubernetes.io/instance: stackfood-orders
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: stackfood
    app: stackfood-orders
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: stackfood-orders
    app: stackfood-orders
